name: Android CI

on:
  push:
    branches: [ "main" ]
    paths:
      - android-client/**
      - '*.json'
      - .github/workflows/android.yml 
  pull_request:
    branches: [ "main" ]
    paths:
      - android-client/**
      - '*.json'
      - .github/workflows/android.yml 

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: android-client

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
      
    - name: Static Analysis
      run: ./gradlew ktlintCheck detekt
