name: Android CI

on:
  push:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/android-so.yml 
  pull_request:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/android-so.yml 

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: android-so

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
      
    - name: Static Analysis
      run: ./gradlew ktlintCheck detekt
      
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Releasing using Hub
      uses: kyze8439690/action-release-releaseapk@master
      env:
       GITHUB_TOKEN: ${{ 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 }}
       APP_FOLDER: app
    

   
